version: 0.2

# buildspec for downloading required source code to S3 - as part of codepipeline build

phases:
  install:
    runtime-versions:
      # https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html
      nodejs: 18
    commands:
      - echo install

      - echo "install terraform"
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.7.4/terraform_1.7.4_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
    finally:
      - terraform --version
#     we only work within code
      - cd amplify/application

  post_build:
    commands:
      - echo post_build

      - echo "initialize terraform"
      - echo $ARTIFACTS
      - echo $NAME_PREFIX

      - terraform init -backend-config="bucket=$ARTIFACTS"

      - echo "apply terraform"
      - terraform apply -auto-approve -var "name_prefix=$NAME_PREFIX"

      - touch init.tfvars
      - printf "bucket=\"$ARTIFACTS\"" > init.tfvars
      - touch application.tfvars
      - printf "name_prefix=\"$NAME_PREFIX\"" > application.tfvars

      - aws s3 cp init.tfvars s3://${ARTIFACTS}/init.tfvars
      - aws s3 cp application.tfvars s3://${ARTIFACTS}/application.tfvars